### PR TITLE
#327 - Go back to repository list when adding/edit

### PR DESCRIPTION
**Pull request by Juyoo**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev** (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Make sure that you've add licence text on every new file you are adding to repository.

### Description
 Go back to repository list when adding/edit

*Please describe your pull request.
If possible provide visual elements to illustrate your feature and*

Thank you for your contribution ! :tropical_drink:

### CODE REVIEW

**Comment by yodamad** [comment]
@Juyoo Can you fix frontend

**Comment by Juyoo** [comment]
@yodamad yes, i'm trying find the error, because i think that my change is not a breaking change, and the "ng build" works well locally.

The problem may be in the Semaphoreci build, we have this statement "yarn global add @angular/cli" that dowload the version 6.1.5 release 8 days ago.
To fix this problem, it could be interesting to download the @angular/cli version put on the package.json by replacing "yarn global add @angular/cli" by "yarn global add @angular/cli@6.0.8".

Because i would like wait the release of [this PR](https://github.com/BTMorton/angular2-grid/pull/295) before upgrading the full package.

**Comment by yodamad** [comment]
Tried with 6.0.8, still failing

**Comment by Juyoo** [comment]
It should be ok now, the problem came to the new version of RXJS, if you want to know more about it : https://github.com/angular/flex-layout/issues/827

Should be fixed tomorrow

**Pull request merged**
