### PR TITLE
WIP: Issue #93 - Swagger api configuration changes

### PR DESCRIPTION
**Pull request by milankamboya**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev** (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Description
Please describe your pull request.
If possible provide visual elements to illustrate your feature and 

Thank you for your contribution ! :tropical_drink:

### Description for this PR :
- Added configuration for swagger rest docs.
- As of now allowed swagger url without authentication.
- Added swagger annotation for only one controller. If this PR looks good to maintainers then will do those changes for all controllers.

### CODE REVIEW

**Comment by milankamboya** [comment]
Swagger changes will look like below screen-shot. Let me know if anything needs to change.
image

**Comment by milankamboya** [comment]
Added licence on new java file.

**Comment by yodamad** [comment]
@milankamboya : the build is broken on your PR. I've cloned your repo, and there are some invalid characters in your pom.xml.
Can you check that and reformat the file.

Thanks

**Comment by milankamboya** [comment]
Done, build passes. Didn't get what issue exactly. But after re-adding last dependency, it didn't show the error.

**Comment by yodamad** [comment]
I'd like to limit swagger usage to dev mode.
Do you prefer to update PR to add swagger initialization only when dev profile activated or create another PR ?

**Comment by milankamboya** [comment]
Sure. But can you help me few things about

**Comment by yodamad** [comment]
@Juyoo Can u help @milankamboya about authent, plz

**Comment by yodamad** [comment]
Up @Juyoo

**Comment by milankamboya** [comment]
hi @Juyoo , how to generate new user's password as bcrypt? is there any java file to generate this password? I didn't find any.
There is one demo user and its password. 
But I am not able to use that. 
Can you mail me decrypted pass ? or is there any other way?

**Comment by milankamboya** [comment]
Hi @yodamad , I have added changes to enable swagger in dev profile only.
Check it and let me know if anything else needed.

**Comment by yodamad** [comment]
Ok.
I let the PR opened if you want to continue with new APIs support and/or security support

**Comment by milankamboya** [comment]
@yodamad Thanx.

**Pull request merged**
